#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Keedo_Project.Resource", IsApplication=true)]

namespace Keedo_Project
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Keedo_Project.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Keedo_Project.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Keedo_Project.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040028
			public const int AuthorName = 2130968616;
			
			// aapt resource value: 0x7f040005
			public const int BasketButtonMain = 2130968581;
			
			// aapt resource value: 0x7f040016
			public const int BookAuthor = 2130968598;
			
			// aapt resource value: 0x7f04002d
			public const int BookInfo = 2130968621;
			
			// aapt resource value: 0x7f040007
			public const int BookOrder = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int BookPrice = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int BookPurchase = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int BookTitle = 2130968597;
			
			// aapt resource value: 0x7f040026
			public const int BoughtFrom = 2130968614;
			
			// aapt resource value: 0x7f040025
			public const int BoughtFromText = 2130968613;
			
			// aapt resource value: 0x7f04002c
			public const int BuyBook = 2130968620;
			
			// aapt resource value: 0x7f04002a
			public const int CollectDirect = 2130968618;
			
			// aapt resource value: 0x7f04000c
			public const int CollectFrom = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int CollectFromText = 2130968587;
			
			// aapt resource value: 0x7f04002b
			public const int CollectKeedo = 2130968619;
			
			// aapt resource value: 0x7f04001d
			public const int Email = 2130968605;
			
			// aapt resource value: 0x7f040013
			public const int ExampleImage = 2130968595;
			
			// aapt resource value: 0x7f04001b
			public const int FirstName = 2130968603;
			
			// aapt resource value: 0x7f040021
			public const int Grid = 2130968609;
			
			// aapt resource value: 0x7f04000f
			public const int HorizLine = 2130968591;
			
			// aapt resource value: 0x7f04001c
			public const int LastName = 2130968604;
			
			// aapt resource value: 0x7f040004
			public const int LibraryHeader = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int MainToolbar = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MenuButtonMain = 2130968579;
			
			// aapt resource value: 0x7f040024
			public const int OrderDetails = 2130968612;
			
			// aapt resource value: 0x7f04000a
			public const int OrderID = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int OrderIDText = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int OrderLayout = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int OrderTotal = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int OrderTotalText = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int OrdersButtonMain = 2130968582;
			
			// aapt resource value: 0x7f04001e
			public const int Purchase = 2130968606;
			
			// aapt resource value: 0x7f040014
			public const int PurchaseBookLayout = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int PurchaseLayout = 2130968601;
			
			// aapt resource value: 0x7f040001
			public const int ReturnButton = 2130968577;
			
			// aapt resource value: 0x7f040020
			public const int ScanButton = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int SearchBar = 2130968607;
			
			// aapt resource value: 0x7f040023
			public const int TestText = 2130968611;
			
			// aapt resource value: 0x7f04001a
			public const int UserDetails = 2130968602;
			
			// aapt resource value: 0x7f04002e
			public const int contentFrame = 2130968622;
			
			// aapt resource value: 0x7f040000
			public const int layout = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int linearLayout1 = 2130968592;
			
			// aapt resource value: 0x7f040029
			public const int radioGroup1 = 2130968617;
			
			// aapt resource value: 0x7f040011
			public const int tableLayout1 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int tableRow1 = 2130968594;
			
			// aapt resource value: 0x7f040027
			public const int tableRow2 = 2130968615;
			
			// aapt resource value: 0x7f040022
			public const int testImage = 2130968610;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AllOrders = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BuyBook = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Model = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int OrderDetails = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Product = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int zxingscanneractivitylayout = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int zxingscannerfragmentlayout = 2130837511;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
